services:
  postgres-db:
    image: postgres:15.4
    container_name: fitbuddy_postgres
    environment:
      POSTGRES_DB: fitbuddy_db
      POSTGRES_USER: fitbuddy_user
      POSTGRES_PASSWORD: fitbuddy_password
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1.0'  # Maximum CPU allocation
          memory: 512M  # Maximum memory allocation
        reservations:
          cpus: '0.5'  # Minimum CPU allocation
          memory: 256M  # Minimum memory allocation

  app:
    image: eclipse-temurin:21-jdk
    container_name: fitbuddy_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/fitbuddy_db
      SPRING_DATASOURCE_USERNAME: fitbuddy_user
      SPRING_DATASOURCE_PASSWORD: fitbuddy_password
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'  # Maximum CPU allocation
          memory: 512M  # Maximum memory allocation
        reservations:
          cpus: '0.5'  # Minimum CPU allocation
          memory: 256M  # Minimum memory allocation

volumes:
  postgres_data:
